var Showdown={};
Showdown.converter=function(){var h,i,o,p=0;this.makeHtml=function(a){h=[];i=[];o=[];a=a.replace(/~/g,"~T");a=a.replace(/\$/g,"~D");a=a.replace(/\r\n/g,"\n");a=a.replace(/\r/g,"\n");a="\n\n"+a+"\n\n";a=v(a);a=a.replace(/^[ \t]+$/mg,"");a=w(a);a=C(a);a=q(a);a=x(a);a=a.replace(/~D/g,"$$");a=a.replace(/~T/g,"~");a=a.replace(/https?\:\/\/[^"\s\<\>]*[^.,;'">\:\s\<\>\)\]\!]/g,function(b){var c=RegExp.rightContext;if(RegExp.leftContext.match(/<[^>]+$/)&&c.match(/^[^>]*>/))return b;return"<a href='"+b+"'>"+
b+"</a>"});return a=a.replace(/[a-z0-9_\-+=.]+@[a-z0-9\-]+(\.[a-z0-9-]+)+/ig,function(b){return"<a href='mailto:"+b+"'>"+b+"</a>"})};var C=function(a){return a=a.replace(/^[ ]{0,3}\[(.+)\]:[ \t]*\n?[ \t]*<?(\S+?)>?[ \t]*\n?[ \t]*(?:(\n*)["(](.+?)[")][ \t]*)?(?:\n+|\Z)/gm,function(b,c,d,e,g){c=c.toLowerCase();h[c]=y(d);if(e)return e+g;else if(g)i[c]=g.replace(/"/g,"&quot;");return""})},w=function(a){a=a.replace(/\n/g,"\n\n");a=a.replace(/^(<(p|div|h[1-6]|blockquote|pre|table|dl|ol|ul|script|noscript|form|fieldset|iframe|math|ins|del)\b[^\r]*?\n<\/\2>[ \t]*(?=\n+))/gm,
m);a=a.replace(/^(<(p|div|h[1-6]|blockquote|pre|table|dl|ol|ul|script|noscript|form|fieldset|iframe|math)\b[^\r]*?.*<\/\2>[ \t]*(?=\n+)\n)/gm,m);a=a.replace(/(\n[ ]{0,3}(<(hr)\b([^<>])*?\/?>)[ \t]*(?=\n{2,}))/g,m);a=a.replace(/(\n\n[ ]{0,3}<!(--[^\r]*?--\s*)+>[ \t]*(?=\n{2,}))/g,m);a=a.replace(/(?:\n\n)([ ]{0,3}(?:<([?%])[^\r]*?\2>)[ \t]*(?=\n{2,}))/g,m);return a=a.replace(/\n\n/g,"\n")},m=function(a,b){var c=b;c=c.replace(/\n\n/g,"\n");c=c.replace(/^\n/,"");c=c.replace(/\n+$/g,"");return c="\n\n~K"+
(o.push(c)-1)+"K\n\n"},q=function(a){a=D(a);var b=j("<hr />");a=a.replace(/^[ ]{0,2}([ ]?\*[ ]?){3,}[ \t]*$/gm,b);a=a.replace(/^[ ]{0,2}([ ]?\-[ ]?){3,}[ \t]*$/gm,b);a=a.replace(/^[ ]{0,2}([ ]?\_[ ]?){3,}[ \t]*$/gm,b);a=z(a);a=E(a);a=F(a);a=a=w(a);a=a.replace(/^\n+/g,"");a=a.replace(/\n+$/g,"");var c=a.split(/\n{2,}/g);a=[];b=c.length;for(var d=0;d<b;d++){var e=c[d];if(e.search(/~K(\d+)K/g)>=0)a.push(e);else if(e.search(/\S/)>=0){e=n(e);e=e.replace(/^([ \t]*)/g,"<p>");e+="</p>";a.push(e)}}b=a.length;
for(d=0;d<b;d++)for(;a[d].search(/~K(\d+)K/)>=0;){c=o[RegExp.$1];c=c.replace(/\$/g,"$$$$");a[d]=a[d].replace(/~K\d+K/,c)}return a=a.join("\n\n")},n=function(a){a=G(a);a=a=H(a);a=a.replace(/\\(\\)/g,r);a=a=a=a.replace(/\\([`*_{}\[\]()>#+-.!])/g,r);a=a.replace(/(!\[(.*?)\][ ]?(?:\n[ ]*)?\[(.*?)\])()()()()/g,A);a=a=a=a.replace(/(!\[(.*?)\]\s?\([ \t]*()<?(\S+?)>?[ \t]*((['"])(.*?)\6[ \t]*)?\))/g,A);a=a.replace(/(\[((?:\[[^\]]*\]|[^\[\]])*)\][ ]?(?:\n[ ]*)?\[(.*?)\])()()()()/g,s);a=a.replace(/(\[((?:\[[^\]]*\]|[^\[\]])*)\]\([ \t]*()<?(.*?)>?[ \t]*((['"])(.*?)\6[ \t]*)?\))/g,
s);a=a=a.replace(/(\[([^\[\]]+)\])()()()()()/g,s);a=I(a);a=a=y(a);a=a.replace(/(\*\*|__)(?=\S)([^\r]*?\S[*_]*)\1/g,"<strong>$2</strong>");a=a.replace(/(\w)_(\w)/g,"$1~E95E$2");a=a=a.replace(/(\*|_)(?=\S)([^\r]*?\S)\1/g,"<em>$2</em>");return a=a.replace(/  +\n/g," <br />\n")},H=function(a){return a=a.replace(/(<[a-z\/!$]("[^"]*"|'[^']*'|[^'">])*>|<!(--.*?--\s*)+>)/gi,function(b){b=b.replace(/(.)<\/?code>(?=.)/g,"$1`");return b=k(b,"\\`*_")})},s=function(a,b,c,d,e,g,l,f){if(f==undefined)f="";a=d.toLowerCase();
e=e;f=f;if(e==""){if(a=="")a=c.toLowerCase().replace(/ ?\n/g," ");if(h[a]!=undefined){e=h[a];if(i[a]!=undefined)f=i[a]}else if(b.search(/\(\s*\)$/m)>-1)e="";else return b}e=k(e,"*_");b='<a href="'+e+'"';if(f!=""){f=f.replace(/"/g,"&quot;");f=k(f,"*_");b+=' title="'+f+'"'}b+=">"+c+"</a>";return b},A=function(a,b,c,d,e,g,l,f){a=c;d=d.toLowerCase();e=e;(f=f)||(f="");if(e==""){if(d=="")d=a.toLowerCase().replace(/ ?\n/g," ");if(h[d]!=undefined){e=h[d];if(i[d]!=undefined)f=i[d]}else return b}a=a.replace(/"/g,
"&quot;");e=k(e,"*_");b='<img src="'+e+'" alt="'+a+'"';f=f.replace(/"/g,"&quot;");f=k(f,"*_");b+=' title="'+f+'"';b+=" />";return b},D=function(a){a=a.replace(/^(.+)[ \t]*\n=+[ \t]*\n+/gm,function(b,c){return j("<h1>"+n(c)+"</h1>")});a=a.replace(/^(.+)[ \t]*\n-+[ \t]*\n+/gm,function(b,c){return j("<h2>"+n(c)+"</h2>")});return a=a.replace(/^(\#{1,6})[ \t]*(.+?)[ \t]*\#*\n+/gm,function(b,c,d){b=c.length;return j("<h"+b+">"+n(d)+"</h"+b+">")})},t,z=function(a){a+="~0";var b=/^(([ ]{0,3}([*+-]|\d+[.])[ \t]+)[^\r]+?(~0|\n{2,}(?=\S)(?![ \t]*(?:[*+-]|\d+[.])[ \t]+)))/gm;
if(p)a=a.replace(b,function(c,d,e){c=d;e=e.search(/[*+-]/g)>-1?"ul":"ol";c=c.replace(/\n{2,}/g,"\n\n\n");c=t(c);c=c.replace(/\s+$/,"");return c="<"+e+">"+c+"</"+e+">\n"});else{b=/(\n\n|^\n?)(([ ]{0,3}([*+-]|\d+[.])[ \t]+)[^\r]+?(~0|\n{2,}(?=\S)(?![ \t]*(?:[*+-]|\d+[.])[ \t]+)))/g;a=a.replace(b,function(c,d,e,g){c=e;g=g.search(/[*+-]/g)>-1?"ul":"ol";c=c.replace(/\n{2,}/g,"\n\n\n");c=t(c);return c=d+"<"+g+">\n"+c+"</"+g+">\n"})}return a=a.replace(/~0/,"")};t=function(a){p++;a=a.replace(/\n{2,}$/,"\n");
a+="~0";a=a.replace(/(\n)?(^[ \t]*)([*+-]|\d+[.])[ \t]+([^\r]+?(\n{1,2}))(?=\n*(~0|\2([*+-]|\d+[.])[ \t]+))/gm,function(b,c,d,e,g){b=g;if(c||b.search(/\n{2,}/)>-1)b=q(u(b));else{b=z(u(b));b=b.replace(/\n$/,"");b=n(b)}return"<li>"+b+"</li>\n"});a=a.replace(/~0/g,"");p--;return a};var E=function(a){a+="~0";a=a.replace(/(?:\n\n|^)((?:(?:[ ]{4}|\t).*\n+)+)(\n*[ ]{0,3}[^ \t\n]|(?=~0))/g,function(b,c,d){b=c;b=B(u(b));b=v(b);b=b.replace(/^\n+/g,"");b=b.replace(/\n+$/g,"");b="<pre><code>"+b+"\n</code></pre>";
return j(b)+d});return a=a.replace(/~0/,"")},j=function(a){a=a.replace(/(^\n+|\n+$)/g,"");return"\n\n~K"+(o.push(a)-1)+"K\n\n"},G=function(a){return a=a.replace(/(^|[^\\])(`+)([^\r]*?[^`])\2(?!`)/gm,function(b,c,d,e){b=e;b=b.replace(/^([ \t]*)/g,"");b=b.replace(/[ \t]*$/g,"");b=B(b);return c+"<code>"+b+"</code>"})},B=function(a){a=a.replace(/&/g,"&amp;");a=a.replace(/</g,"&lt;");a=a.replace(/>/g,"&gt;");return a=k(a,"*_{}[]\\",false)},F=function(a){return a=a.replace(/((^[ \t]*>[ \t]?.+\n(.+\n)*\n*)+)/gm,
function(b,c){var d=c;d=d.replace(/^[ \t]*>[ \t]?/gm,"~0");d=d.replace(/~0/g,"");d=d.replace(/^[ \t]+$/gm,"");d=q(d);d=d.replace(/(^|\n)/g,"$1  ");d=d.replace(/(\s*<pre>[^\r]+?<\/pre>)/gm,function(e,g){var l=g;l=l.replace(/^  /mg,"~0");return l=l.replace(/~0/g,"")});return j("<blockquote>\n"+d+"\n</blockquote>")})},y=function(a){a=a.replace(/&(?!#?[xX]?(?:[0-9a-fA-F]+|\w+);)/g,"&amp;");return a=a.replace(/<(?![a-z\/?\$!])/gi,"&lt;")},I=function(a){a=a.replace(/<((https?|ftp|dict):[^'">\s]+)>/gi,'<a href="$1">$1</a>');
return a=a.replace(/<(?:mailto:)?([-.\w]+\@[-a-z0-9]+(\.[-a-z0-9]+)*\.[a-z]+)>/gi,function(b,c){return J(x(c))})},J=function(a){var b=[function(c){return"&#"+c.charCodeAt(0)+";"},function(c){c=c.charCodeAt(0);return"&#x"+("0123456789ABCDEF".charAt(c>>4)+"0123456789ABCDEF".charAt(c&15))+";"},function(c){return c}];a="mailto:"+a;a=a.replace(/./g,function(c){if(c=="@")c=b[Math.floor(Math.random()*2)](c);else if(c!=":"){var d=Math.random();c=d>0.9?b[2](c):d>0.45?b[1](c):b[0](c)}return c});a='<a href="'+
a+'">'+a+"</a>";return a=a.replace(/">.+:/g,'">')},x=function(a){return a=a.replace(/~E(\d+)E/g,function(b,c){var d=parseInt(c);return String.fromCharCode(d)})},u=function(a){a=a.replace(/^(\t|[ ]{1,4})/gm,"~0");return a=a.replace(/~0/g,"")},v=function(a){a=a.replace(/\t(?=\t)/g,"    ");a=a.replace(/\t/g,"~A~B");a=a.replace(/~B(.+?)~A/g,function(b,c){for(var d=c,e=4-d.length%4,g=0;g<e;g++)d+=" ";return d});a=a.replace(/~A/g,"    ");return a=a.replace(/~B/g,"")},k=function(a,b,c){b="(["+b.replace(/([\[\]\\])/g,
"\\$1")+"])";if(c)b="\\\\"+b;c=RegExp(b,"g");return a=a.replace(c,r)},r=function(a,b){return"~E"+b.charCodeAt(0)+"E"}};